---
title: '992'
output: html_document
---



```{r}
library(grDevices)
library(Matrix)
library(rARPACK)
library(plyr)
suppressPackageStartupMessages(library(dplyr))
library(ggplot2)
library(grid)
library(data.table)
library(sand) 
library(network)
#library(sna)
library(igraph)


```




```{r}
load("~/Dropbox/STAT992/DataSource/Dat.RData")
load("~/Dropbox/STAT992/DataSource/Et.RData")
load("~/Dropbox/STAT992/DataSource/Midwest.RData")
setkey(Et, V1) 
setkey(Dat, NPI) 
```

First want to foucs on one state

```{r}
data.referral = Dat[`NPPES Provider State` %in% c("IA","IL","IN","KS","MI" ,"MN","MO","ND","NE","OH","SD","WI")]
tmp.link = Et[unique(data.referral$NPI)] #link two data sets
tmp.link = tmp.link[complete.cases(tmp.link)] 
tmp.link<-tmp.link[which(tmp.link$V2 %in% data.referral$NPI)]  
# only keep the vertice in midwest and individual
referral.matrix= as.matrix(tmp.link)[,1:2]
referral.undirected.graph= graph.edgelist(referral.matrix,directed=F)
referral.undirected.graph= simplify(referral.undirected.graph) #simplify the graph
```

### 可先不管core

```{r}
core.referral.graph = graph.coreness(referral.undirected.graph) #get core
referral.graph = induced.subgraph(graph=referral.undirected.graph,vids=V(referral.undirected.graph)[core.referral.graph>0])


hist(core.referral.graph)
sum(core.referral.graph > 30)
referral.graph = induced.subgraph(graph=referral.undirected.graph,vids=V(referral.undirected.graph)[core.referral.graph>30])
#locs = layout.fruchterman.reingold(referral.graph)
locs = layout.out(referral.graph)
plot(referral.graph,vertex.size=6,layout=locs,edge.arrow.size=0.05,vertex.label=NA, main = "Network Graph")
```

graph property

```{r}
deg.graph<-degree(referral.undirected.graph)
eigen_central<-evcent(referral.undirected.graph)$vector  # eigenvector centrality score
eigen_central<-closeness(referral.undirected.graph)$vector
bet<-betweenness(referral.undirected.graph)
close<-closeness(referral.undirected.graph)

```

Dat attribute

```{r}
referral.frame.data<-data.referral[V(referral.undirected.graph)]
payment<-referral.frame.data$`Total Medicare Payment Amount`
number.beneficiaries<-referral.frame.data$`Number of Unique Beneficiaries`
number.service<-referral.frame.data$`Number of Services`
average.age.wisc<-referral.frame.data$`Average Age of Beneficiaries`
```


```{r}
frame<-data.frame(V(referral.undirected.graph)$name,deg.graph,eigen_central)
colnames(frame)<-c("NPI","degree","central_score")
frame$NPI<-as.character(frame$NPI)
```


for procedure


```{r}
Bypass.frame<-frame[which(frame$NPI %in% Bypass$NPI),]
mm<-match(Bypass$NPI,frame$NPI)
frame<-complete.cases(frame[match(Bypass$NPI,frame$NPI),]) 
Bypass.frame.all<-cbind(Bypass.frame,Bypass$average_Medicare_payment_amt,Bypass$Difference)
```


model

```{r}
fit1<-lm(payment.wisc~deg.graph.wisc+eigen_central+average.age.wisc+number.service.wisc)
summary(fit1)
```


